alias rails-f0='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-feature-0" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text) "sudo docker exec -it \$(sudo docker ps | grep 8080/tcp | awk '\''{print \$1}'\'') rails c"'
alias rails-f1='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-feature-1" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text) "sudo docker exec -it \$(sudo docker ps | grep 8080/tcp | awk '\''{print \$1}'\'') rails c"'
alias rails-f2='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-feature-2-with-reporting" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text) "sudo docker exec -it \$(sudo docker ps | grep 8080/tcp | awk '\''{print \$1}'\'') rails c"'
alias rails-qa='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-qa" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text) "sudo docker exec -it \$(sudo docker ps | grep 8080/tcp | awk '\''{print \$1}'\'') rails c"'
alias rails-reporting='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-reporting" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text) "sudo docker exec -it \$(sudo docker ps | grep 8080/tcp | awk '\''{print \$1}'\'') rails c"'
alias rails-prod='ssh -t -i "~/.ssh/ec2-kayzen-console-production.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-production-jobs" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text | head -n 1) "sudo docker exec -it \$(sudo docker ps | grep 8080/tcp | awk '\''{print \$1}'\'' | head -n 1) rails c"'

alias ssh-f0='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-feature-0" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text)'
alias ssh-f1='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-feature-1" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text)'
alias ssh-f2='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-feature-2-with-reporting" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text)'
alias ssh-qa='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-qa" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text)'
alias ssh-reporting='ssh -t -i "~/.ssh/ec2-kayzen-development.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-reporting" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text)'
alias ssh-prod='ssh -t -i "~/.ssh/ec2-kayzen-console-production.pem" ec2-user@$(aws ec2 describe-instances --filter "Name=tag:Name,Values=kayzen-production-jobs" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text | head -n 1)'

